### ISSUE TITLE
Incompatible with protobuf 30.0

### ISSUE THREAD

**Issue by christian-heusel** [protobuf-c/protobuf-c#766]
Hello, Arch Linux Packager here 👋🏻 

We have recently started the [protobuf 30.0](https://archlinux.org/todo/protobuf-300/) rebuild and the protobuf-c package is one of the holdups that came up along the way due to the following compiler error:

```
protoc-c/c_helpers.cc: In function ‘std::string google::protobuf::compiler::c::FieldName(const google::protobuf::FieldDescriptor*)’:
protoc-c/c_helpers.cc:298:43: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘google::protobuf::internal::DescriptorStringView’ {aka ‘std::basic_string_view<char>’}
  298 |   std::string result = ToLower(field->name());
      |                                ~~~~~~~~~~~^~
protoc-c/c_helpers.cc:155:40: note: in passing argument 1 of ‘std::string google::protobuf::compiler::c::ToLower(const std::string&)’
  155 | std::string ToLower(const std::string &name) {
      |                     ~~~~~~~~~~~~~~~~~~~^~~~
protoc-c/c_enum.cc: In member function ‘void google::protobuf::compiler::c::EnumGenerator::GenerateDefinition(google::protobuf::io::Printer*)’:
```

It would be awesome if someone could look into it, I'm not familiar enough with the two codebases to come up with a patch on my own 😅 

cc @lfos

**Comment by edmonds** [comment]
That particular error should be fixed by https://github.com/protobuf-c/protobuf-c/pull/762 but I believe there are more things broken by protobuf 30.0-rc2 or 30.0 final.

**Comment by christian-heusel** [comment]
Yeah  there are more cases it seems:
```
  CXX      t/generated_code2_cxx_generate_packed_data-test-full.pb.o
protoc-gen-c/c_enum.cc: In member function ‘void protobuf_c::EnumGenerator::GenerateDefinition(google::protobuf::io::Printer*)’:
protoc-gen-c/c_enum.cc:83:57: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘google::protobuf::internal::DescriptorStringView’ {aka ‘std::basic_string_view<char>’}
   83 |   vars["classname"] = FullNameToC(descriptor_->full_name(), descriptor_->file());
      |                                   ~~~~~~~~~~~~~~~~~~~~~~^~
In file included from protoc-gen-c/c_enum.cc:69:
protoc-gen-c/c_helpers.h:128:44: note: in passing argument 1 of ‘std::string protobuf_c::FullNameToC(const std::string&, const google::protobuf::FileDescriptor*)’
  128 | std::string FullNameToC(const std::string &class_name, const google::protobuf::FileDescriptor *file);
      |                         ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
protoc-gen-c/c_enum.cc:85:59: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘google::protobuf::internal::DescriptorStringView’ {aka ‘std::basic_string_view<char>’}
   85 |   vars["uc_name"] = FullNameToUpper(descriptor_->full_name(), descriptor_->file());
      |                                     ~~~~~~~~~~~~~~~~~~~~~~^~
protoc-gen-c/c_helpers.h:125:48: note: in passing argument 1 of ‘std::string protobuf_c::FullNameToUpper(const std::string&, const google::protobuf::FileDescriptor*)’
  125 | std::string FullNameToUpper(const std::string &full_name, const google::protobuf::FileDescriptor *file);
      |                             ~~~~~~~~~~~~~~~~~~~^~~~~~~~~
protoc-gen-c/c_enum.cc:99:58: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘google::protobuf::internal::DescriptorStringView’ {aka ‘std::basic_string_view<char>’}
   99 |   vars["prefix"] = FullNameToUpper(descriptor_->full_name(), descriptor_->file()) + "__";
      |                                    ~~~~~~~~~~~~~~~~~~~~~~^~
protoc-gen-c/c_helpers.h:125:48: note: in passing argument 1 of ‘std::string protobuf_c::FullNameToUpper(const std::string&, const google::protobuf::FileDescriptor*)’
  125 | std::string FullNameToUpper(const std::string &full_name, const google::protobuf::FileDescriptor *file);
      |                             ~~~~~~~~~~~~~~~~~~~^~~~~~~~~
protoc-gen-c/c_enum.cc: In member function ‘void protobuf_c::EnumGenerator::GenerateDescriptorDeclarations(google::protobuf::io::Printer*)’:
protoc-gen-c/c_enum.cc:133:57: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘google::protobuf::internal::DescriptorStringView’ {aka ‘std::basic_string_view<char>’}
  133 |   vars["classname"] = FullNameToC(descriptor_->full_name(), descriptor_->file());
      |                                   ~~~~~~~~~~~~~~~~~~~~~~^~
protoc-gen-c/c_helpers.h:128:44: note: in passing argument 1 of ‘std::string protobuf_c::FullNameToC(const std::string&, const google::protobuf::FileDescriptor*)’
  128 | std::string FullNameToC(const std::string &class_name, const google::protobuf::FileDescriptor *file);
      |                         ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
protoc-gen-c/c_enum.cc:134:63: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘google::protobuf::internal::DescriptorStringView’ {aka ‘std::basic_string_view<char>’}
  134 |   vars["lcclassname"] = FullNameToLower(descriptor_->full_name(), descriptor_->file());
      |                                         ~~~~~~~~~~~~~~~~~~~~~~^~
protoc-gen-c/c_helpers.h:124:48: note: in passing argument 1 of ‘std::string protobuf_c::FullNameToLower(const std::string&, const google::protobuf::FileDescriptor*)’
  124 | std::string FullNameToLower(const std::string &full_name, const google::protobuf::FileDescriptor *file);
      |                             ~~~~~~~~~~~~~~~~~~~^~~~~~~~~
protoc-gen-c/c_enum.cc: In member function ‘void protobuf_c::EnumGenerator::GenerateValueInitializer(google::protobuf::io::Printer*, int)’:
protoc-gen-c/c_enum.cc:155:69: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘google::protobuf::internal::DescriptorStringView’ {aka ‘std::basic_string_view<char>’}
  155 |   vars["c_enum_value_name"] = FullNameToUpper(descriptor_->full_name(), descriptor_->file()) + "__" + vd->name();
      |                                               ~~~~~~~~~~~~~~~~~~~~~~^~
protoc-gen-c/c_helpers.h:125:48: note: in passing argument 1 of ‘std::string protobuf_c::FullNameToUpper(const std::string&, const google::protobuf::FileDescriptor*)’
  125 | std::string FullNameToUpper(const std::string &full_name, const google::protobuf::FileDescriptor *file);
      |                             ~~~~~~~~~~~~~~~~~~~^~~~~~~~~
protoc-gen-c/c_enum.cc: In member function ‘void protobuf_c::EnumGenerator::GenerateEnumDescriptor(google::protobuf::io::Printer*)’:
protoc-gen-c/c_enum.cc:185:63: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘google::protobuf::internal::DescriptorStringView’ {aka ‘std::basic_string_view<char>’}
  185 |   vars["lcclassname"] = FullNameToLower(descriptor_->full_name(), descriptor_->file());
      |                                         ~~~~~~~~~~~~~~~~~~~~~~^~
protoc-gen-c/c_helpers.h:124:48: note: in passing argument 1 of ‘std::string protobuf_c::FullNameToLower(const std::string&, const google::protobuf::FileDescriptor*)’
  124 | std::string FullNameToLower(const std::string &full_name, const google::protobuf::FileDescriptor *file);
      |                             ~~~~~~~~~~~~~~~~~~~^~~~~~~~~
protoc-gen-c/c_enum.cc:186:53: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘google::protobuf::internal::DescriptorStringView’ {aka ‘std::basic_string_view<char>’}
  186 |   vars["cname"] = FullNameToC(descriptor_->full_name(), descriptor_->file());
      |                               ~~~~~~~~~~~~~~~~~~~~~~^~
protoc-gen-c/c_helpers.h:128:44: note: in passing argument 1 of ‘std::string protobuf_c::FullNameToC(const std::string&, const google::protobuf::FileDescriptor*)’
  128 | std::string FullNameToC(const std::string &class_name, const google::protobuf::FileDescriptor *file);
      |                         ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
protoc-gen-c/c_enum.cc:202:37: error: ‘google::protobuf::internal::DescriptorStringView’ {aka ‘class std::basic_string_view<char>’} has no member named ‘c_str’; did you mean ‘const char* std::basic_string_view<char>::_M_str’? (not accessible from this context)
  202 |     name_index[j].name = vd->name().c_str();
      |                                     ^~~~~
In file included from /usr/include/c++/14.2.1/bits/basic_string.h:47,
                 from /usr/include/c++/14.2.1/string:54,
                 from /usr/include/google/protobuf/io/printer.h:20,
                 from protoc-gen-c/c_enum.cc:66:
/usr/include/c++/14.2.1/string_view:584:21: note: declared private here
  584 |       const _CharT* _M_str;
      |                     ^~~~~~
protoc-gen-c/c_enum.cc:205:38: error: ‘google::protobuf::internal::DescriptorStringView’ {aka ‘class std::basic_string_view<char>’} has no member named ‘c_str’; did you mean ‘const char* std::basic_string_view<char>::_M_str’? (not accessible from this context)
  205 |     value_index[j].name = vd->name().c_str();
      |                                      ^~~~~
/usr/include/c++/14.2.1/string_view:584:21: note: declared private here
  584 |       const _CharT* _M_str;
      |                     ^~~~~~
protoc-gen-c/c_helpers.cc: In function ‘std::string protobuf_c::FieldName(const google::protobuf::FieldDescriptor*)’:
protoc-gen-c/c_helpers.cc:296:43: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘google::protobuf::internal::DescriptorStringView’ {aka ‘std::basic_string_view<char>’}
  296 |   std::string result = ToLower(field->name());
      |                                ~~~~~~~~~~~^~
protoc-gen-c/c_helpers.cc:157:40: note: in passing argument 1 of ‘std::string protobuf_c::ToLower(const std::string&)’
  157 | std::string ToLower(const std::string &name) {
      |                     ~~~~~~~~~~~~~~~~~~~^~~~
protoc-gen-c/c_message.cc: In member function ‘void protobuf_c::MessageGenerator::GenerateStructTypedef(google::protobuf::io::Printer*)’:
protoc-gen-c/c_message.cc:117:65: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘google::protobuf::internal::DescriptorStringView’ {aka ‘std::basic_string_view<char>’}
  117 |                  "classname", FullNameToC(descriptor_->full_name(), descriptor_->file()));
      |                                           ~~~~~~~~~~~~~~~~~~~~~~^~
In file included from protoc-gen-c/c_message.cc:79:
protoc-gen-c/c_helpers.h:128:44: note: in passing argument 1 of ‘std::string protobuf_c::FullNameToC(const std::string&, const google::protobuf::FileDescriptor*)’
  128 | std::string FullNameToC(const std::string &class_name, const google::protobuf::FileDescriptor *file);
      |                         ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
protoc-gen-c/c_message.cc: In member function ‘void protobuf_c::MessageGenerator::GenerateStructDefinition(google::protobuf::io::Printer*)’:
protoc-gen-c/c_message.cc:143:57: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘google::protobuf::internal::DescriptorStringView’ {aka ‘std::basic_string_view<char>’}
  143 |   vars["classname"] = FullNameToC(descriptor_->full_name(), descriptor_->file());
```

Full build (error) log: 

[protobuf-c-1.5.1-1-x86_64-build.log](https://github.com/user-attachments/files/19169445/protobuf-c-1.5.1-1-x86_64-build.log)

**Comment by rahulc07** [comment]
Hi I'm a Linux From Scratch editor, verbatim same error.

**Comment by xry111** [comment]
Please apply #762.

**Comment by christian-heusel** [comment]
@xry111 sadly #762 is not enough, I applied the full `master..next` diff and still get compiler errors 😅 
```
protoc-gen-c/c_helpers.cc: In function ‘std::string protobuf_c::FieldName(const google::protobuf::FieldDescriptor*)’:
protoc-gen-c/c_helpers.cc:296:43: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘google::protobuf::internal::DescriptorStringView’ {aka ‘std::basic_string_view<char>’}
  296 |   std::string result = ToLower(field->name());
      |                                ~~~~~~~~~~~^~
protoc-gen-c/c_helpers.cc:157:40: note: in passing argument 1 of ‘std::string protobuf_c::ToLower(const std::string&)’
  157 | std::string ToLower(const std::string &name) {
      |                     ~~~~~~~~~~~~~~~~~~~^~~~
protoc-gen-c/c_bytes_field.cc: In function ‘void protobuf_c::SetBytesVariables(const google::protobuf::FieldDescriptor*, std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >*)’:
protoc-gen-c/c_bytes_field.cc:78:52: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘google::protobuf::internal::DescriptorStringView’ {aka ‘std::basic_string_view<char>’}
   78 |     "\"" + CEscape(descriptor->default_value_string()) + "\"";
      |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from protoc-gen-c/c_bytes_field.cc:70:
protoc-gen-c/c_helpers.h:88:40: note: in passing argument 1 of ‘std::string protobuf_c::CEscape(const std::string&)’
   88 | std::string CEscape(const std::string& src);
      |                     ~~~~~~~~~~~~~~~~~~~^~~
protoc-gen-c/c_bytes_field.cc: In member function ‘virtual void protobuf_c::BytesFieldGenerator::GenerateDefaultValueDeclarations(google::protobuf::io::Printer*) const’:
protoc-gen-c/c_bytes_field.cc:115:70: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘google::protobuf::internal::DescriptorStringView’ {aka ‘std::basic_string_view<char>’}
  115 |   vars["default_value_data"] = FullNameToLower(descriptor_->full_name(), descriptor_->file())
      |                                                ~~~~~~~~~~~~~~~~~~~~~~^~
protoc-gen-c/c_helpers.h:124:48: note: in passing argument 1 of ‘std::string protobuf_c::FullNameToLower(const std::string&, const google::protobuf::FileDescriptor*)’
  124 | std::string FullNameToLower(const std::string &full_name, const google::protobuf::FileDescriptor *file);
      |                             ~~~~~~~~~~~~~~~~~~~^~~~~~~~~
protoc-gen-c/c_bytes_field.cc: In member function ‘virtual void protobuf_c::BytesFieldGenerator::GenerateDefaultValueImplementations(google::protobuf::io::Printer*) const’:
protoc-gen-c/c_bytes_field.cc:123:70: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘google::protobuf::internal::DescriptorStringView’ {aka ‘std::basic_string_view<char>’}
  123 |   vars["default_value_data"] = FullNameToLower(descriptor_->full_name(), descriptor_->file())
      |                                                ~~~~~~~~~~~~~~~~~~~~~~^~
protoc-gen-c/c_helpers.h:124:48: note: in passing argument 1 of ‘std::string protobuf_c::FullNameToLower(const std::string&, const google::protobuf::FileDescriptor*)’
  124 | std::string FullNameToLower(const std::string &full_name, const google::protobuf::FileDescriptor *file);
      |                             ~~~~~~~~~~~~~~~~~~~^~~~~~~~~
protoc-gen-c/c_bytes_field.cc:125:62: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘google::protobuf::internal::DescriptorStringView’ {aka ‘std::basic_string_view<char>’}
  125 |   vars["escaped"] = CEscape(descriptor_->default_value_string());
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
protoc-gen-c/c_helpers.h:88:40: note: in passing argument 1 of ‘std::string protobuf_c::CEscape(const std::string&)’
   88 | std::string CEscape(const std::string& src);
      |                     ~~~~~~~~~~~~~~~~~~~^~~
protoc-gen-c/c_bytes_field.cc: In member function ‘virtual std::string protobuf_c::BytesFieldGenerator::GetDefaultValue() const’:
protoc-gen-c/c_bytes_field.cc:133:49: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘google::protobuf::internal::DescriptorStringView’ {aka ‘std::basic_string_view<char>’}
  133 |         + FullNameToLower(descriptor_->full_name(), descriptor_->file())
      |                           ~~~~~~~~~~~~~~~~~~~~~~^~
protoc-gen-c/c_helpers.h:124:48: note: in passing argument 1 of ‘std::string protobuf_c::FullNameToLower(const std::string&, const google::protobuf::FileDescriptor*)’
  124 | std::string FullNameToLower(const std::string &full_name, const google::protobuf::FileDescriptor *file);
      |                             ~~~~~~~~~~~~~~~~~~~^~~~~~~~~
protoc-gen-c/c_message.cc: In member function ‘void protobuf_c::MessageGenerator::GenerateStructTypedef(google::protobuf::io::Printer*)’:
protoc-gen-c/c_message.cc:117:65: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘google::protobuf::internal::DescriptorStringView’ {aka ‘std::basic_string_view<char>’}
  117 |                  "classname", FullNameToC(descriptor_->full_name(), descriptor_->file()));
      |                                           ~~~~~~~~~~~~~~~~~~~~~~^~
In file included from protoc-gen-c/c_message.cc:79:
protoc-gen-c/c_helpers.h:128:44: note: in passing argument 1 of ‘std::string protobuf_c::FullNameToC(const std::string&, const google::protobuf::FileDescriptor*)’
  128 | std::string FullNameToC(const std::string &class_name, const google::protobuf::FileDescriptor *file);
      |                         ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
protoc-gen-c/c_message.cc: In member function ‘void protobuf_c::MessageGenerator::GenerateStructDefinition(google::protobuf::io::Printer*)’:
protoc-gen-c/c_message.cc:143:57: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘google::protobuf::internal::DescriptorStringView’ {aka ‘std::basic_string_view<char>’}
  143 |   vars["classname"] = FullNameToC(descriptor_->full_name(), descriptor_->file());
      |                                   ~~~~~~~~~~~~~~~~~~~~~~^~
protoc-gen-c/c_helpers.h:128:44: note: in passing argument 1 of ‘std::string protobuf_c::FullNameToC(const std::string&, const google::protobuf::FileDescriptor*)’
  128 | std::string FullNameToC(const std::string &class_name, const google::protobuf::FileDescriptor *file);
      |                         ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
protoc-gen-c/c_message.cc:144:63: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘google::protobuf::internal::DescriptorStringView’ {aka ‘std::basic_string_view<char>’}
  144 |   vars["lcclassname"] = FullNameToLower(descriptor_->full_name(), descriptor_->file());
      |                                         ~~~~~~~~~~~~~~~~~~~~~~^~
protoc-gen-c/c_helpers.h:124:48: note: in passing argument 1 of ‘std::string protobuf_c::FullNameToLower(const std::string&, const google::protobuf::FileDescriptor*)’
  124 | std::string FullNameToLower(const std::string &full_name, const google::protobuf::FileDescriptor *file);
      |                             ~~~~~~~~~~~~~~~~~~~^~~~~~~~~
```

**Comment by edmonds** [comment]
The `next` branch (i.e. #762 + #768) should fix compatibility with protobuf 30.x while maintaining compatibility with older versions. If someone can test out the `next` branch and confirm I will go ahead and release 1.5.2.

**Comment by botovq** [comment]
@edmonds I have run a few tests with the `next` branch at 63dee703731cbd3cc143058bc539e4b313a72810 and protobuf 30.1 and things appear to work fine.
Also, all consumers in the OpenBSD ports tree appear to work.

**Comment by edmonds** [comment]
Fix released in https://github.com/protobuf-c/protobuf-c/releases/tag/v1.5.2
